### ISSUE TITLE
Integrate Firebase Authentication in Flutter application

### ISSUE THREAD

**Issue by nadinekuo** [GDSC-Delft-Dev/apa#13]
- [ ] Add dependencies to project
- [ ] Ensure correct user data is fetched upon logging in

**Comment by paulmis** [comment]
Is this set up @nadinekuo? I saw we have a branch for this issue

**Comment by nadinekuo** [comment]
I don't know about any branch on this issue hahha? Anyways I am starting this issue right now ;)
