### ISSUE TITLE
Update Github documentation

### ISSUE THREAD

**Issue by paulmis** [GDSC-Delft-Dev/apa#86]
We should update the technical project documentation on Github. Let's revamp the `READMES` and add a wiki on the following parts of code:

Main readme
- [x] Terrafarm description + logo
- [x] Features
- [x] Installation
- [x] Usage
- [x] Dependencies
- [x] Main structure
- [x] How to contribute

Backend
- [x] Pipeline
- [x] CI/CD
- [x] Segmentation
- [x] Index modules
- [x] Insight modules

Frontend:
- [X] All model types and maybe validation or constraints on them.
- [X] Providers
- [X] Services
- [X] Stores
- [ ] Cloud functions if we make any

**Comment by paulmis** [comment]
@mirceatlx @nadinekuo @RD211 can we add what should be described about the frontend/rest of the backend?

**Comment by nadinekuo** [comment]
Yes definitely, although our frontend structure is not definite yet so let's iteratively add what we can? @RD211

**Comment by RD211** [comment]
I suppose we have the following structure that we could maybe add docs for?

- [ ] All model types and maybe validation or constraints on them.
- [ ] Providers
- [ ] Services
- [ ] Stores

**Comment by nadinekuo** [comment]
> I suppose we have the following structure that we could maybe add docs for?
> 
> * [ ]  All model types and maybe validation or constraints on them.
> * [ ]  Providers
> * [ ]  Services
> * [ ]  Stores
> * [ ]  Cloud functions if we make any

A general structure overview in the READ ME already, but we can have separate subsections for each of these

**Comment by RD211** [comment]
> A general structure overview in the READ ME already, but we can have separate subsections for each of these

Yup that was what I was thinking of. This should cover almost everything of the functionality as we do not do anything complex yet. We can just expand on the info about each Provider/Service/Stores
