### ISSUE TITLE
Details page for localized insights

### ISSUE THREAD

**Issue by nadinekuo** [GDSC-Delft-Dev/apa#96]
When clicking on some marker, either open a subpage or bottom sheet to show:

- [ ] Details of detected issue
- [ ] Potential remedies
- [ ] Optional: image of issue

Related: #26

**Comment by paulmis** [comment]
Can you think of a mechanism to display details about the different kinds of information we'd like to display for various insights? E.g. when it comes to pest detection, we probably want the English name, proper name, image of the pest, and example image(s) of the pest reference, and the area of the field affected. 

However, for standing water we wouldn't have the reference images, and it's probably more important to highlight the affected area.

**Comment by nadinekuo** [comment]
I will also modify the data architecture in Lucid
